export declare function prepareData(data: any, newFeatures: any): any;
export declare function setupYScales(height: any, padding: any, features: any, newDataset: any): any;
export declare function setupXScales(width: any, padding: any, features: any): any;
export declare function setupYAxis(yScales: any, newDataset: any, hiddenDims: any): any;
export declare function linePath(d: any, newFeatures: any, parcoords: any): any;
export declare function isInverted(dimension: string): boolean;
export declare function createToolTipForValues(recordData: any): void;
export declare function getAllPointerEventsData(event: any, hoverlabel: string): any;
export declare function createTooltipForPathLine(tooltipText: any, tooltipPath: any, event: any): any;
export declare function trans(g: any): any;
export declare function position(dimensionName: any, dragging: any, xScales: any): any;
export declare function cleanTooltip(): void;
