export const originalColumns = [
  { key: "Patient", label: "Patient", type: "string" },
  { key: "Age", label: "Age", type: "number" },
  { key: "BloodPressure", label: "Blood Pressure", type: "number" },
  { key: "HeartRate", label: "Heart Rate", type: "number" },
  { key: "BMI", label: "BMI", type: "number" },
  { key: "Cholesterol", label: "Cholesterol", type: "number" },
  { key: "FitnessScore", label: "Fitness Score", type: "number" },
  { key: "Treatment", label: "Treatment", type: "string" },
];

export const originalRows = [
  {
    Patient: "Patient A",
    Age: 42,
    BloodPressure: 110,
    HeartRate: 70,
    BMI: 22,
    Cholesterol: 170,
    FitnessScore: 95,
    Treatment: "A",
  },
  {
    Patient: "Patient B",
    Age: 48,
    BloodPressure: 118,
    HeartRate: 73,
    BMI: 24,
    Cholesterol: 185,
    FitnessScore: 90,
    Treatment: "A",
  },
  {
    Patient: "Patient C",
    Age: 53,
    BloodPressure: 125,
    HeartRate: 75,
    BMI: 25,
    Cholesterol: 200,
    FitnessScore: 85,
    Treatment: "A",
  },
  {
    Patient: "Patient D",
    Age: 60,
    BloodPressure: 145,
    HeartRate: 68,
    BMI: 29,
    Cholesterol: 260,
    FitnessScore: 65,
    Treatment: "B",
  },
  {
    Patient: "Patient E",
    Age: 63,
    BloodPressure: 150,
    HeartRate: 66,
    BMI: 31,
    Cholesterol: 280,
    FitnessScore: 60,
    Treatment: "B",
  },
  {
    Patient: "Patient F",
    Age: 70,
    BloodPressure: 165,
    HeartRate: 58,
    BMI: 34,
    Cholesterol: 600,
    FitnessScore: 55,
    Treatment: "B",
  },
];

export const columnsStudent = [
  { key: "Name", label: "Name", type: "string" },
  { key: "Maths", label: "Maths", type: "number" },
  { key: "English", label: "English", type: "number" },
  { key: "PE", label: "PE", type: "number" },
  { key: "Art", label: "Art", type: "number" },
  { key: "History", label: "History", type: "number" },
  { key: "IT", label: "IT", type: "number" },
  { key: "Biology", label: "Biology", type: "number" },
  { key: "German", label: "German", type: "number" },
];

export const rowsStudent = [
  {
    Name: "Adrian",
    Maths: 95,
    English: 24,
    PE: 82,
    Art: 49,
    History: 58,
    IT: 85,
    Biology: 21,
    German: 24,
  },
  {
    Name: "Amelia",
    Maths: 45,
    English: 120,
    PE: 72,
    Art: 25,
    History: 200,
    IT: 85,
    Biology: 21,
    German: 24,
  },
  {
    Name: "Patient A",
    Maths: 45,
    English: 120,
    PE: 72,
    Art: 25,
    History: 200,
    IT: 85,
    Biology: 21,
    German: 24,
  },
  {
    Name: "Patient A",
    Maths: 45,
    English: 120,
    PE: 72,
    Art: 25,
    History: 200,
    IT: 85,
    Biology: 21,
    German: 24,
  },
  {
    Name: "Patient A",
    Maths: 45,
    English: 120,
    PE: 72,
    Art: 25,
    History: 200,
    IT: 85,
    Biology: 21,
    German: 24,
  },
  {
    Name: "Patient A",
    Maths: 45,
    English: 120,
    PE: 72,
    Art: 25,
    History: 200,
    IT: 85,
    Biology: 21,
    German: 24,
  },
  {
    Name: "Patient A",
    Maths: 45,
    English: 120,
    PE: 72,
    Art: 25,
    History: 200,
    IT: 85,
    Biology: 21,
    German: 24,
  },
  {
    Name: "Patient A",
    Maths: 45,
    English: 120,
    PE: 72,
    Art: 25,
    History: 200,
    IT: 85,
    Biology: 21,
    German: 24,
  },
  {
    Name: "Patient A",
    Maths: 45,
    English: 120,
    PE: 72,
    Art: 25,
    History: 200,
    IT: 85,
    Biology: 21,
    German: 24,
  },
  {
    Name: "Patient A",
    Maths: 45,
    English: 120,
    PE: 72,
    Art: 25,
    History: 200,
    IT: 85,
    Biology: 21,
    German: 24,
  },
  {
    Name: "Patient A",
    Maths: 45,
    English: 120,
    PE: 72,
    Art: 25,
    History: 200,
    IT: 85,
    Biology: 21,
    German: 24,
  },
  {
    Name: "Patient A",
    Maths: 45,
    English: 120,
    PE: 72,
    Art: 25,
    History: 200,
    IT: 85,
    Biology: 21,
    German: 24,
  },
  {
    Name: "Patient A",
    Maths: 45,
    English: 120,
    PE: 72,
    Art: 25,
    History: 200,
    IT: 85,
    Biology: 21,
    German: 24,
  },
  {
    Name: "Patient A",
    Maths: 45,
    English: 120,
    PE: 72,
    Art: 25,
    History: 200,
    IT: 85,
    Biology: 21,
    German: 24,
  },
  {
    Name: "Patient A",
    Maths: 45,
    English: 120,
    PE: 72,
    Art: 25,
    History: 200,
    IT: 85,
    Biology: 21,
    German: 24,
  },
  {
    Name: "Patient A",
    Maths: 45,
    English: 120,
    PE: 72,
    Art: 25,
    History: 200,
    IT: 85,
    Biology: 21,
    German: 24,
  },
  {
    Name: "Patient A",
    Maths: 45,
    English: 120,
    PE: 72,
    Art: 25,
    History: 200,
    IT: 85,
    Biology: 21,
    German: 24,
  },
  {
    Name: "Patient A",
    Maths: 45,
    English: 120,
    PE: 72,
    Art: 25,
    History: 200,
    IT: 85,
    Biology: 21,
    German: 24,
  },
  {
    Name: "Patient A",
    Maths: 45,
    English: 120,
    PE: 72,
    Art: 25,
    History: 200,
    IT: 85,
    Biology: 21,
    German: 24,
  },
  {
    Name: "Patient A",
    Maths: 45,
    English: 120,
    PE: 72,
    Art: 25,
    History: 200,
    IT: 85,
    Biology: 21,
    German: 24,
  },
  {
    Name: "Patient A",
    Maths: 45,
    English: 120,
    PE: 72,
    Art: 25,
    History: 200,
    IT: 85,
    Biology: 21,
    German: 24,
  },
  {
    Name: "Patient A",
    Maths: 45,
    English: 120,
    PE: 72,
    Art: 25,
    History: 200,
    IT: 85,
    Biology: 21,
    German: 24,
  },
  {
    Name: "Patient A",
    Maths: 45,
    English: 120,
    PE: 72,
    Art: 25,
    History: 200,
    IT: 85,
    Biology: 21,
    German: 24,
  },
  {
    Name: "Patient A",
    Maths: 45,
    English: 120,
    PE: 72,
    Art: 25,
    History: 200,
    IT: 85,
    Biology: 21,
    German: 24,
  },
  {
    Name: "Patient A",
    Maths: 45,
    English: 120,
    PE: 72,
    Art: 25,
    History: 200,
    IT: 85,
    Biology: 21,
    German: 24,
  },
  {
    Name: "Patient A",
    Maths: 45,
    English: 120,
    PE: 72,
    Art: 25,
    History: 200,
    IT: 85,
    Biology: 21,
    German: 24,
  },
  {
    Name: "Patient A",
    Maths: 45,
    English: 120,
    PE: 72,
    Art: 25,
    History: 200,
    IT: 85,
    Biology: 21,
    German: 24,
  },
  {
    Name: "Patient A",
    Maths: 45,
    English: 120,
    PE: 72,
    Art: 25,
    History: 200,
    IT: 85,
    Biology: 21,
    German: 24,
  },
  {
    Name: "Patient A",
    Maths: 45,
    English: 120,
    PE: 72,
    Art: 25,
    History: 200,
    IT: 85,
    Biology: 21,
    German: 24,
  },
  {
    Name: "Patient A",
    Maths: 45,
    English: 120,
    PE: 72,
    Art: 25,
    History: 200,
    IT: 85,
    Biology: 21,
    German: 24,
  },
];

export const columnsFinance = [
  { key: "Name", label: "Name", type: "string" },
  { key: "Income", label: "Income (€)", type: "number" },
  { key: "Accomodation", label: "Accomodation (€)", type: "number" },
  { key: "Living", label: "Living (€)", type: "number" },
];

export const rowsFinance = [
  { Name: "Alice", Income: 3500, Accomodation: 1200, Living: 2300 },
  { Name: "Bob", Income: 2800, Accomodation: 900, Living: 1900 },
  { Name: "Charlie", Income: 4200, Accomodation: 1500, Living: 2700 },
  { Name: "Fiona", Income: 2700, Accomodation: 800, Living: 1900 },
  { Name: "Ursula", Income: 6000, Accomodation: 500, Living: 5500 },
  { Name: "Victor", Income: 3400, Accomodation: 1100, Living: 2300 },
];
