name: Deploy to GitHub Pages via docs/

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '18'
          cache: 'yarn'

      - name: Install dependencies
        run: yarn install

      - name: Build with Vite
        run: yarn build

      - name: Copy build to docs/
        run: |
          rm -rf docs
          mkdir docs
          cp -r dist/* docs/

      - name: Add .nojekyll to prevent Jekyll processing
        run: touch docs/.nojekyll

      - name: Commit and push changes
        run: |
          git config user.name "github-actions[bot]"
          git config user.email "github-actions[bot]@users.noreply.github.com"
          git add docs
          git commit -m "Deploy to GitHub Pages"
          git push origin main
