name: Deploy to GitHub Pages

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Check Node version
        run: node -v

      - name: Check Yarn version
        run: yarn -v

      - name: Show current directory
        run: pwd

      - name: List root files
        run: ls -la

      - name: Show vite.config.js content
        run: cat vite.config.js

      - name: Install dependencies
        run: yarn install

      - name: Build project
        run: yarn build

      - name: List build output
        run: find dist -type f

      - name: Show dist/index.html
        run: cat dist/index.html || echo "index.html not found"

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: "dist/"

  deploy:
    needs: build
    runs-on: ubuntu-latest
    permissions:
      pages: write
      id-token: write
    environment:
      name: github-pages
      url: ${{ steps.deploy-pages.outputs.page_url }}
    steps:
      - name: Deploy to GitHub Pages
        id: deploy-pages
        uses: actions/deploy-pages@v4
